[default.extend-words]
MOR = "MOR"
dum = "dum"
Shepard = "Shepard"
arange = "arange"
iy = "iy"
iz = "iz"
nin = "nin"
tect = "tect"

[files]
extend-exclude = ["tutorials/*.pvsm","docs/paper/paper.bib"]
